### ISSUE TITLE
SmartThings Not Responding

### ISSUE THREAD

**Issue by cjuarbe** [beckyricha/Broadlink-RM-LAN-Control#23]

**Comment by beckyricha** [comment]
Hi. I noticed it says closed. Is this because you solved it? If not, the issue (or at least one issue) is the ip address. For the cloud version you will need to use an external ip address, so it won't start with 192.
Hope this helps (or that you got it working already).
Becky
On Feb 24, 2017 9:38 PM, cjuarbe <notifications@github.com> wrote:Hello, I have set everything up as instructed. However, when I say Alexa turn bedroom light on it looks like it is trying to communicate with the "device" and then responds with "Bedroom light is not responding". How can I fix this? Using cloud.
Just retried is and now it says "that command does not work on device bedroom light"
Help :(
Here is some info in my set up:
Smartthings Device List:
Bedroom Light	RM Bridge Switch Cloud	Home			Bedroom Light	ACTIVE
Bedroom Light 2	RM Bridge Switch Cloud	Home			Bedroom Light 2	ACTIVE
cable	RM Bridge Switch Cloud	Home			cable	ACTIVE
End of RM Bridge Switch Code:
private put(toggle) {
def toReplace = device.deviceNetworkId
def replaced = toReplace.replaceAll(' ', '%20')
def params = [
uri: "http://192.168.1.10:7474/code/$replaced%20$toggle"
]
httpGet(params)
}
Bedroom Light Device Info:
Name	Bedroom Light
Label
Type	RM Bridge Switch Cloud
Version	Published
Device Network Id	Bedroom Light
Status	ACTIVE
Last Activity At	2017-02-25 2:00 AM UTC
Date Created	2017-02-25 2:00 AM UTC
Last Updated	2017-02-25 2:00 AM UTC
Data	No data found for device
Current States
switch: off
Events	List Events
In Use By
RM Bridge Codes:
Bedroom Light 2 off	34:ea:34:e7:ec:c1	http://192.168.1.10:7474/code/Bedroom Light 2 off
Bedroom Light 2 on	34:ea:34:e7:ec:c1	http://192.168.1.10:7474/code/Bedroom Light 2 on
Bedroom Light off	34:ea:34:e7:ec:c1	http://192.168.1.10:7474/code/Bedroom Light off
Bedroom Light on	34:ea:34:e7:ec:c1	http://192.168.1.10:7474/code/Bedroom Light on
cable off	34:ea:34:e7:ec:c1	http://192.168.1.10:7474/code/cable off
cable on	34:ea:34:e7:ec:c1	http://192.168.1.10:7474/code/cable on
All devices loaded in Alexa
Devices work when do test in RM Bridge
Devices do not work in Smartthings app
Devices work when put http in web browser
