### ISSUE TITLE
Almost certainly something I am missing.  Can't get ST to control the RM2

### ISSUE THREAD

**Issue by Martin1973X** [beckyricha/Broadlink-RM-LAN-Control#29]
I have the remote code programmed using the RM. 
![rm bridge](https://cloud.githubusercontent.com/assets/25872085/26272609/79275b88-3ce2-11e7-8dd3-687fe2043011.PNG)

The code is listed as tvswitch and works from the test button. (I'm not concerned about posting a class C internal IP) 
The code I am using is the LAN version and seems to be configured as suggested. 

![code](https://cloud.githubusercontent.com/assets/25872085/26272628/213b0900-3ce3-11e7-8f36-f3aca2fa6393.PNG)

`The device seems to be set up, but no communication to the RM2 or output from ST. 

![fina](https://cloud.githubusercontent.com/assets/25872085/26272636/837e9f82-3ce3-11e7-9e81-b09a6f3b4e42.PNG)

![tvswitch](https://cloud.githubusercontent.com/assets/25872085/26272642/9c14166c-3ce3-11e7-9799-17e21525a444.PNG)

The configuration SHOULD toggle the TV on / off when used, but no output from the RM. No debug info when using the switch under a simulator. 

![sim](https://cloud.githubusercontent.com/assets/25872085/26272665/0a8224a4-3ce4-11e7-9049-7c4a0cb8bf3b.PNG)

I get the nagging feeling I am missing something which should be obvious but just can't seem to get there. Any suggestions or help would be appreciated. The switch shows up in the ST app, just doesn't do anything. RM firmware is 20025, the RM works fine with everything else, including visiting the http address in the first image at which point I get the response "{"code":0,"msg":"rm2 send data success"}" and the TV mode toggles (on or off) . 

EDIT - ignore the transposed port address, I did change it to the correct one of 7474 and still nothing. Been working on this for two days. 

Oh, and the app says it's controlling the switch. 

![device events](https://cloud.githubusercontent.com/assets/25872085/26273683/488e79bc-3cfa-11e7-93a7-0e6d8691424a.PNG)

**Comment by beckyricha** [comment]
I didn't get through the whole message just yet as I'm out of the house, but on first glance I think the problem is with your code names. Your code name must end with a space and the word on or off. If you want it to do both, you need one called tvswitch on and another called tvswitch off, even if it's the same toggle switch.On May 19, 2017 11:42 PM, Martin1973X <notifications@github.com> wrote:I have the remote code programmed using the RM.

The code is listed as tvswitch and works from the test button. (I'm not concerned about posting a class C internal IP)
The code I am using is the LAN version and seems to be configured as suggested.

`The device seems to be set up, but no communication to the RM2 or output from ST.


The configuration SHOULD toggle the TV on / off when used, but no output from the RM. No debug info when using the switch under a simulator.

I get the nagging feeling I am missing something which should be obvious but just can't seem to get there. Any suggestions or help would be appreciated. The switch shows up in the ST app, just doesn't do anything. RM firmware is 20025, the RM works fine with everything else, including visiting the http address in the first image.

**Comment by Martin1973X** [comment]
Got it,  thanks. The issue was that the RM switch code needs to be stored with on and off as the title but the ST device does not.

Example - for my device tvswitch. The stored remote code on the RM Code Manager site needs two stored codes

tvswitch on
tvswitch off

BUT the ST Device manager just needs to be 

tvswitch

Thanks for the help, all is working as it should now. I said it was probably something I was missing.
