### ISSUE TITLE
Location - Create device

### ISSUE THREAD

**Issue by mesterila** [beckyricha/Broadlink-RM-LAN-Control#46]
Hello Becky,
My first time ever on github - looking for a solution for the failing RMTasker(Pro) - Alexa can't discover devices published through it anymore, even though RMTasker can control them, eControl works fine, ihc as well. Your code seems to be doing the trick, so if this works you've got all my praise! :)

I got stuck at step #12 on your guide. I created Device Handlers, SmartApp, I have a location called "Home" with the Samsung TV in it. I am aware I need to create a device (which I can see you created a code for) but I guess this functionality (from code) has been removed. 

So now I go to "Create Device" manually, select "broadlinkswitch" as Type, "Home" as location, but I don't know what to chose for "Device Network ID* ". Is this the Wifi SSID or something else ? And once this is done with "Create" - your guide ends. What would be the next step? How would I "run" this code on the bridge (old Samsung phone where RMTasker is also running)?

Thank you very much for this work! Fingers crossed it works!

**Comment by beckyricha** [comment]
Hi - i have switched over to the broadlink's direct Alexa integration through their app,  so haven't used these scripts for a couple of years.  i need to update the GitHub info to reflect that, but can still try to help. I'll just need to get back up to speed on it.   If you haven't explored that broadlink's direct option, I'd start there. I can control all my devices without anything besides the broadlink's ehc app.  I did need to re-record remotes, though.  i am in a training class so will look this over later this evening. i can't guarantee things still work, though.  Which code are you using? is it the one for tasker or rmbridge? i seriously doubt the tasker one will still work, as I maintained it less than the other. Because it was a paid option where a free one existed, most of my effort and the community contributions went towards the RMBridge version.thanks.BeckyOn Jan 8, 2020 4:00 AM, mesterila <notifications@github.com> wrote:Hello Becky,
My first time ever on github - looking for a solution for the failing RMTasker(Pro) - Alexa can't discover devices published through it anymore, even though RMTasker can control them, eControl works fine, ihc as well. Your code seems to be doing the trick, so if this works you've got all my praise! :)
I got stuck at step #12 on your guide. I created Device Handlers, SmartApp, I have a location called "Home" with the Samsung TV in it. I am aware I need to create a device (which I can see you created a code for) but I guess this functionality (from code) has been removed.
So now I go to "Create Device" manually, select "broadlinkswitch" as Type, "Home" as location, but I don't know what to chose for "Device Network ID* ". Is this the Wifi SSID or something else ? And once this is done with "Create" - your guide ends. What would be the next step? How would I "run" this code on the bridge (old Samsung phone where RMTasker is also running)?
Thank you very much for this work! Fingers crossed it works!

**Comment by mesterila** [comment]
Thank you Becky! I did try the Alexa skill first, like you suggested (integration with IHC) but that doesn't work with any devices controlled over radio (433MHz) and most of mine are as such - Broadlink wall switches. It only works with IR devices (TV and sound system)."I did need to re-record remotes, though." - I had also done this before, due to the radio switches, so the remotes are there, but unfortunately don't work with Alexa. I was using RMTasker (the paid version), but I don't mind changing to anything else that allows Alexa to control these radio switches. Would be great to have this working again one way or another. Alex

**Comment by beckyricha** [comment]
the app works great with rf 433 MHz devices. that's all i use.On Jan 8, 2020 9:03 AM, mesterila <notifications@github.com> wrote:Thank you Becky! I did try the Alexa skill first, like you suggested (integration with IHC) but that doesn't work with any devices controlled over radio (433MHz) and most of mine are as such - Broadlink wall switches. It only works with IR devices (TV and sound system)."I did need to re-record remotes, though." - I had also done this before, due to the radio switches, so the remotes are there, but unfortunately don't work with Alexa. I was using RMTasker (the paid version), but I don't mind changing to anything else that allows Alexa to control these radio switches. Would be great to have this working again one way or another. Alex

**Comment by mesterila** [comment]
So I rushed home with new hope and unlinked ihc from Alexa. After testing once again (re-adding all the switches in ihc), a relink to Alexa followed and.... discover devices returned no new devices. Looking further into the Settings tab, it seems that the smart skill "ihc for eu" doesn't support RMPro2, but only RMPro and RMPro3. Already considering to buy the RMPro3...
Thanks for your advice ;)

**Comment by mesterila** [comment]
Fixed. Leaving this here if someone stumbles on this thread:
My Alexa account is on amazon.co.uk, therefore, logically, would need "ihc for EU" skill, which didn't work. As soon as I installed the "ihc" skill, it could discover the devices. Thanks Becky for the bump.
